2020-11-05 14:24:03 WARN  ConnectionUtil:47 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: database " " does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2617)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:135)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:250)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:41)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:26)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:25)
	at com.revature.Driver.main(Driver.java:15)
